### ISSUE TITLE
git clone failed

### ISSUE THREAD

**Issue by JiachnegHo** [NVIDIA-ISAAC-ROS/isaac_ros_nvblox#15]
When I try to build ROS2 natively, when I go to the step of "git clone --recurse-submodules https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_nvblox", an error is displayed
![1651028721(1)](https://user-images.githubusercontent.com/64136295/165431564-8c008251-55f4-413a-bf34-d3f53fab20ca.png)

**Comment by helenol** [comment]
Hmm this looks like a git issue. Could you try these solutions? https://localcoder.org/error-rpc-failed-curl-56-gnutls-recv-error-110-the-tls-connection-was-non
