### ISSUE TITLE
Does nvblox tell you current position in the map?

### ISSUE THREAD

**Issue by cjh1995-ros** [NVIDIA-ISAAC-ROS/isaac_ros_nvblox#18]
First of all, I'm sorry it's a simple question, not an issue related.

There seems to be a part in tsdf that uses visual odometry in the middle to read your thesis and find related materials. 

Can I use that part for navigation?

**Comment by helenol** [comment]
You need to use an external visual (or otherwise) odometry system, nvblox
just consumes the pose output of that. You can check out Nvidia's solution:
https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_visual_slam or any other
open-source frameworks, such as ORBSLAM, etc.

Cheers,
Helen

**Comment by cjh1995-ros** [comment]
@helenol Thank you for the information!
