### ISSUE TITLE
What is that purple area?

### ISSUE THREAD

**Issue by cjh1995-ros** [NVIDIA-ISAAC-ROS/isaac_ros_nvblox#21]
Hello, I am using the package you made well. I have a question during use, what does that purple area mean? I know the others are costmaps. But I'm not sure what the purple zone means or why it occurs.
![Screenshot from 2022-06-10 00-17-30](https://user-images.githubusercontent.com/47180415/172912768-0f8084f9-6326-433a-8c8b-0f65a62e3990.png)

**Comment by helenol** [comment]
The purple area is "lethal obstacle" in nav2. Looks like the issue is that the ground floor is set to too low: in nvblox_nav2/params/nvblox.yaml, try setting `min_height` to a higher value (i.e., 0.1 higher), units are meters.
