### ISSUE TITLE
Clearing voxels beyond a radius

### ISSUE THREAD

**Issue by Veng97** [NVIDIA-ISAAC-ROS/isaac_ros_nvblox#24]
I don't know if this feature already exists within the core library, but is there a method to prune 'far away' voxels or map blocks? :)

**Comment by helenol** [comment]
Hey! Sorry for the slow response, this functionality isn't in yet but we'll add it to the list for the next release! All the blocks are independent so it's as easy as deleting the blocks that are out of range, which is functionality we'll need to add to the core library.

**Comment by hemalshahNV** [comment]
@alexmillane Any comment on if the latest version of nvblox supports this the feature they way it was described here?

**Comment by alexmillane** [comment]
This is now in the library and configurable through the ROS param `map_clearing_radius_m`

**Comment by Veng97** [comment]
Awesome!
