### ISSUE TITLE
-p voxel_size:=0.008 - out of memory

### ISSUE THREAD

**Issue by AndreV84** [NVIDIA-ISAAC-ROS/isaac_ros_nvblox#30]
```
CUDA error = 2 at /home/nvidia/zed_ws/src/isaac_ros_nvblox/nvblox/nvblox/include/nvblox/core/impl/unified_vector_impl.h:209 'cudaMalloc(&new_buffer, sizeof(T) * capacity)'. Error string: out of memory.
```
any solution?

**Comment by alexmillane** [comment]
Building a map at 0.008-sized voxels will use a lot of memory. It's quite possible that you will run out of memory at such a fine resolution.

The next release will add an option to clear the map outside of a radius to recover some memory as you move around in the scene. The next release will be in a couple of weeks. However, whether or not this is actually a feasible solution depends on your application: i.e. do you actually want the full global map, or do you just want some local area.

So your options at the moment are:
1) increase the voxel size
2) clear the map outside some radius to limit growth of the map in memory, when this is available in the near future.
