### ISSUE TITLE
Official ROS1 Support Request

### ISSUE THREAD

**Issue by JonasFrey96** [NVIDIA-ISAAC-ROS/isaac_ros_nvblox#4]
Hello Nvidia,

thanks a lot for your awesome work on Nvblox.
It would be great if you could also provide an official ROS1 wrapper for this package. 
Most deployed robots in research are still operating on ROS1.  

This would be a great enhancement and benefit a large part of the community. 

Best Jonas

**Comment by R-Fehler** [comment]
+1

**Comment by turcantuna** [comment]
+1 This could benefit very well.

**Comment by cynosure4sure** [comment]
+1

**Comment by ctyfang** [comment]
Based on my past experience, this would be a benefit to companies for sure. +1

**Comment by jelavice** [comment]
+1

**Comment by cynosure4sure** [comment]
Ping! to keep the issue alive

**Comment by tutunarsl** [comment]
Is there any news on this topic?

**Comment by hjxwhy** [comment]
Unofficial modified ROS 1, but remove the sim and nav module https://github.com/hjxwhy/nvblox_ros1, just test success on 3dmatch_node, under developing

**Comment by HappySamuel** [comment]
+1

**Comment by hemalshahNV** [comment]
Isaac ROS only supports ROS2 unfortunately as Open Robotics has shifted their efforts away towards Humble and its successors. ROS1 ports from the community are always welcome and shouldn't be too difficult to implement.

**Comment by helenol** [comment]
The wait is over. :) nvblox ROS1 wrappers, not supported by nvidia: https://github.com/ethz-asl/nvblox_ros1/
