### ISSUE TITLE
Is isaac_ros_nvblox suitable for acceleration when used with 3d lidar?

### ISSUE THREAD

**Issue by muratkoc503** [NVIDIA-ISAAC-ROS/isaac_ros_nvblox#45]
Is isaac_ros_nvblox suitable for acceleration speed when used with 3d lidar? How many times does it speed up? Thanks

**Comment by alexmillane** [comment]
I have tested the speed up against [voxblox](https://github.com/ethz-asl/voxblox) on public depth camera datasets. Depending on what components you run and what platform we see between 20-100x speed up (approximately). We'll make these numbers public in the next few months. I would expect that these numbers would be approximately the same for LiDAR.

**Comment by muratkoc503** [comment]
Thank you very much for answer. This is amazing result.

**Comment by alexmillane** [comment]
No worries! Thanks for your interest!
