### ISSUE TITLE
can nvblox ros use lidar as input?

### ISSUE THREAD

**Issue by chivas1000** [NVIDIA-ISAAC-ROS/isaac_ros_nvblox#46]
Hi I'm using nvblox to produce a costmap for my robot to do a navigation
can it inputs Lidar pointcloud data and still works?
also, if I use other lidar based SLAM as a state estimator, would it works?
since the rgbd and double stereo IR camera and RGB camera altogether takes up too much bandwidth
If nvblox can inputs lidar data and so do vslam, then It might be able to just using lidar data.
Is that right or I am missing something?
thanks for any reply.

**Comment by alexmillane** [comment]
nvblox_ros accepts 3D LiDAR input. We are also agnostic as to where the pose estimate comes from, so an (accurate) 3D pose from LiDAR SLAM will work fine.

I am somewhat surprised you have bandwidth problems though. Are you using the realsense? What computer are you running on?

**Comment by chivas1000** [comment]
> nvblox_ros accepts 3D LiDAR input. We are also agnostic as to where the pose estimate comes from, so an (accurate) 3D pose from LiDAR SLAM will work fine.
> 
> I am somewhat surprised you have bandwidth problems though. Are you using the realsense? What computer are you running on?

Hi @alexmillane,
thanks for the reply, and for the bandwidth, I'm using realsense d435i and now I'm transmitting these datas from one computer to another, so smaller bandwidth usage would be appreciated

another question is that can this nvblox map reuse as to the navigation application? since for the navigation loading a map which is already built is more convenient.

Thanks for your reply.

**Comment by alexmillane** [comment]
Ah I see. Your bandwidth limitations now make sense.

The `nvblox_node` exposes a load map service that can be used to load an existing map for navigation.

**Comment by tugbakara** [comment]
> Ah I see. Your bandwidth limitations now make sense.
> 
> The `nvblox_node` exposes a load map service that can be used to load an existing map for navigation.

How can I use this map for navigation2? I couldnt find any example related to this

**Comment by alexmillane** [comment]
We have docs about using this package for navigation on Nova Carter [here](https://nvidia-isaac-ros.github.io/robots/nova_carter.html).

To run it on your own robot, you'll have to adapt the nova carter launchfiles to your robot.

**Comment by tugbakara** [comment]
> [here](https://nvidia-isaac-ros.github.io/robots/nova_carter.html).
I glanced this page but there does not exist isaac_ros-dev package in github and this nova carter tutorial launch files run from packe isaac_ros-dev.  That's why I cannot reach launch files or anyother to implement my robot
