### ISSUE TITLE
How does nvblox node consumes topics of VSLAM node? 

### ISSUE THREAD

**Issue by naitiknakrani** [NVIDIA-ISAAC-ROS/isaac_ros_nvblox#51]
Hi Team,
We are working with Jetson Orin and v0.11.0-dp Isaac ROS GEMS packages.

As per the following image shown, nvblox and vslam is linked via /pose topic (or data).
![image](https://user-images.githubusercontent.com/85004761/212074081-12337a8e-dca5-4e0b-8cbc-bc36bc8bd430.png)

However if I checked ros2 node info /nvblox_node and
![image](https://user-images.githubusercontent.com/85004761/212074527-bef1f5ff-3aa7-4f31-bc2f-199f73c1068e.png)

ros2 node info /visual_slam_node,
![image](https://user-images.githubusercontent.com/85004761/212074652-fb1b51e7-a53a-46ae-b8b6-2ce7bac62fea.png)

it looks like NVBLOX node is subscribed to /pose topic, however VSLAM node is not publishing /pose topic. Also, we can not able to see REMAPPINGS of topics in any of the launch file given in https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_nvblox/tree/v0.11.0-dp/nvblox_nav2/launch or https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_nvblox/tree/v0.11.0-dp/nvblox_examples/nvblox_examples_bringup/launch

How does than nvblox consuming data published by vslam node?

**Comment by naitiknakrani** [comment]
Hi, Is there anyway Nvblox consumes /tf data ?

**Comment by alexmillane** [comment]
You're correct, nvblox consumes the pose produced by VSLAM using the tf tree.

Hopefully that answers your question?

**Comment by naitiknakrani-eic** [comment]
@alexmillane Thanks for the reply.
