### ISSUE TITLE
Isssue while executing VSLAM Node

### ISSUE THREAD

**Issue by rafism1997** [NVIDIA-ISAAC-ROS/isaac_ros_nvblox#52]
Hi Team, 

We are experiencing some issue while executing the vslam node : 

``` ros2 launch nvblox_examples_bringup nvblox_vslam_realsense.launch.py ```

Exact error is : 

```
[component_container-3] Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
[component_container-3]          at line 93 in /opt/ros/humble/src/geometry2/tf2/src/buffer_core.cpp
```
![vslamissue](https://user-images.githubusercontent.com/33804907/214191814-476f7f31-cafe-4fa9-bdd4-4f075244832a.png)

@alexmillane @hemalshahNV @jaiveersinghNV :Tagging for visibility on issue

Regards,
Rafi

**Comment by rafism1997** [comment]
Hi @alexmillane ,

Thanks for the quick response.

Yes i am able to get the raw image data feed from the realsense.

Regards,
Rafi

**Comment by alexmillane** [comment]
What about the topics that vslam+nvblox subscribe to? These are the output topics from the splitter.

**Comment by rafism1997** [comment]
Are you talking about the Nvbloxmesh and other topics... can you specifically point out those??

**Comment by alexmillane** [comment]
Can you view images on the topic `/camera/realsense_splitter_node/output/infra_1`

There's a trouble shooting page here: https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_nvblox/blob/main/docs/troubleshooting-nvblox-vslam-realsense.md

**Comment by rafism1997** [comment]
Hi @alexmillane, 

Output of ``` ros2 topic list ```

```
admin@ubuntu:/workspaces/isaac_ros-dev$ ros2 topic list
/camera/color/camera_info
/camera/color/image_raw
/camera/color/image_raw/compressed
/camera/color/image_raw/compressedDepth
/camera/color/image_raw/theora
/camera/color/metadata
/camera/depth/camera_info
/camera/depth/color/points
/camera/depth/image_rect_raw
/camera/depth/image_rect_raw/compressed
/camera/depth/image_rect_raw/compressedDepth
/camera/depth/image_rect_raw/theora
/camera/depth/metadata
/camera/extrinsics/depth_to_color
/camera/extrinsics/depth_to_depth
/camera/extrinsics/depth_to_infra1
/camera/extrinsics/depth_to_infra2
/camera/imu
/camera/infra1/camera_info
/camera/infra1/image_rect_raw
/camera/infra1/image_rect_raw/compressed
/camera/infra1/image_rect_raw/compressedDepth
/camera/infra1/image_rect_raw/theora
/camera/infra1/metadata
/camera/infra2/camera_info
/camera/infra2/image_rect_raw
/camera/infra2/image_rect_raw/compressed
/camera/infra2/image_rect_raw/compressedDepth
/camera/infra2/image_rect_raw/theora
/camera/infra2/metadata
/camera/realsense_splitter_node/output/depth
/camera/realsense_splitter_node/output/infra_1
/camera/realsense_splitter_node/output/infra_2
/camera/realsense_splitter_node/output/pointcloud
/clicked_point
/goal_pose
/initialpose
/nvblox_node/map_slice
/nvblox_node/map_slice_bounds
/nvblox_node/mesh
/nvblox_node/mesh_marker
/nvblox_node/pointcloud
/parameter_events
/pointcloud
/pose
/rosout
/tf
/tf_static
/transform
/visual_slam/vis/landmarks_cloud
/visual_slam/vis/observations_cloud
```

**Comment by rafism1997** [comment]
Hi @alexmillane , 

I guess so this is the main problem :

``` Do you see the metadata labelled "Frame Laser Pose Mode" (green box above) which should be flicking between 0 and 1 with the emitter. If no, preceded to the section below for Solution 1 - Install DKMS ```

DKMS , i tried to install but was not finding anything relevant to the arm architecture.

Regards, 
Rafi

**Comment by alexmillane** [comment]
Yea the DKMS stuff only applies to x86, unfortunately.

Can you confirm that if you turn on the "Emitter On Off" button in the realsense viewer that you can see the emitter turning on and off?

**Comment by rafism1997** [comment]
Ya @alexmillane , 

Tried that too.. but the data is not visible in rviz

Regards, 
Rafi

**Comment by alexmillane** [comment]
But just to be clear, can you see the emitter flashing on and off in realsense viewer?

**Comment by rafism1997** [comment]
I can see it turning on and off...

**Comment by alexmillane** [comment]
Ok. Yea I've only seen this problem on x86, not on jetson. Can you share some details about the Jetson you're running on? I presume you're following our tutorial process: running in the isaac_ros docker etc?

One potential workaround is to turn the projector off entirely and subscribe to the topics before the splitter. This impacts reconstruction quality though.
