### ISSUE TITLE
where is  /opt/nvidia/tao/tao-converter

### ISSUE THREAD

**Issue by kong9999** [NVIDIA-ISAAC-ROS/isaac_ros_nvblox#60]
I use  the command  pip3 install nvidia-pyindex and pip3 install nvidia-tao  to install it ,but in my computer didn't appear   /opt/nvidia/tao/tao-converter. Can you explain this step in detail.

**Comment by alexmillane** [comment]
We expect you to do the conversion inside the isaac_ros dev container. _Inside_ the container you should find the toa-converter in that location.

**Comment by alexmillane** [comment]
did this work?
