### ISSUE TITLE
What is the car used in this demo?

### ISSUE THREAD

**Issue by Janebek** [NVIDIA-ISAAC-ROS/isaac_ros_nvblox#68]
Hi! Great work of your guys!

I see you guys using nvblox by drving a car around, is this car moving autonomously? If so, what is the type of this car?

**Comment by alexmillane** [comment]
It's moving autonomously :). It's an NVIDIA carter 2: https://docs.nvidia.com/isaac/doc/tutorials/carter_hardware.html

**Comment by Janebek** [comment]
Thanks Alex :)
