### ISSUE TITLE
Cannot see any result from example

### ISSUE THREAD

**Issue by HedgeHao** [NVIDIA-ISAAC-ROS/isaac_ros_nvblox#73]
Following step 1 to 10, I was able to bring up all nodes without any errors. But I can only see image topics from ros bag playback. I try to  monitor some topics under `nvblox_node` (pointcloud2, marker etc.) but got nothing in rviz.

![sc](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_nvblox/assets/8536950/43b5ef36-899c-4f22-a759-3842873d6758)

What am I missing?

**Comment by jaiveersinghNV** [comment]
It seems like you may have forgotten to change the fixed frame from `map` to `odom`. The quickstart includes a [prepared `.rviz` file](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_nvblox/blob/main/nvblox_examples/nvblox_examples_bringup/config/rviz/isaac_sim_example.rviz) that automatically loads an RViz window with all of the appropriate settings arranged for your convenience.
