### ISSUE TITLE
ToF camera integration with Nvblox

### ISSUE THREAD

**Issue by naitiknakrani-eic** [NVIDIA-ISAAC-ROS/isaac_ros_nvblox#79]
Hi Team, 

I am interested to know whether the present pipeline running with VSLAM and NVBLOX can be modified into the following figure?

Here, I want to use depth of ToF camera and Infra1 and Infra2 of Realsense. I want to reconstruct 3D environment with ToF instead of Realsense. Note: I am putting both camera on stack. 

![Picture1](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_nvblox/assets/117731413/0dca26ee-ec78-4d2a-b3ba-a763a7e75a84)

Are there any limitations or logical reasoning that it shouldn't work ?

**Comment by naitiknakrani-eic** [comment]
Hi, 

Please find the attached image. I tried to feed depth data from ToF into NVBLOX with wheel odometry as a input. Typically with Realsense it works (with only depth data). 

Is there any recommendation to resolve the working of NVBLOX reconstruction using ToF's depth data?

![Screenshot from 2023-10-16 18-06-27](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_nvblox/assets/117731413/c3357701-8acd-4bcd-81a2-1ed9f417a941)

Right side shows the logs of NVBLOX and left side shows the depth data feed.

**Comment by alexmillane** [comment]
The usual reason for getting no reconstruction is:
- A topic mismatch.
- A missing link between the sensor frame and the mapping frame on the TF tree.

Could you check if the depth topic is correctly mapped such that depth images are arriving at nvblox? Then I would check if a link exists between your depth optical frame (which is specified in the `frame_id` entry in your depth image header), and the mapping frame, which is by default `odom`.

**Comment by naitiknakrani-eic** [comment]
Hi @alexmillane Thank you for your quick response and apologies for not giving enough info. 

I am sharing topics name, topics info, changes done in files in this post.

First, my camera topics are:
> /cam1/depth_image_nvblox
> /cam1/camera_info_sync
and my camera frame id is > "camera_link_optical"

 **Topics mismatch**
I have remapped two topics in https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_nvblox/blob/v2.0.0/nvblox_examples/nvblox_examples_bringup/launch/nvblox/nvblox.launch.py
<img width="267" alt="topic_remap" src="https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_nvblox/assets/117731413/9d61ed62-250d-48b5-87c1-224c022489bb">

and changed frame id in config file given at https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_nvblox/blob/v2.0.0/nvblox_examples/nvblox_examples_bringup/config/nvblox/specializations/nvblox_realsense.yaml
<img width="340" alt="config" src="https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_nvblox/assets/117731413/1acf4961-f571-4a8d-a7b8-5898378d08db">

I have checked weather the data is arriving and proper? It seems perfect as shown in below image.
<img width="556" alt="topic hz" src="https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_nvblox/assets/117731413/37c55a19-e810-45d8-9f3a-10f497413d2d">
<img width="202" alt="Topic info" src="https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_nvblox/assets/117731413/751e6eaf-f01e-4761-b830-90505c203957">

**A missing link between the sensor frame and the mapping frame on the TF tree.**

Once I launched the node, I checked TF tree. Here is the image showing my TF tree.
<img width="782" alt="tf_tree" src="https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_nvblox/assets/117731413/aedaf77d-440d-4de3-bada-8981903db500">

Let me know If I missed to provide any information.

**Comment by naitiknakrani-eic** [comment]
Note that I have tested it in both v.2.0 and v0.31.0-dp.

**Comment by naitiknakrani-eic** [comment]
Hi @alexmillane any inputs/suggestions ?

**Comment by ashwinvkNV** [comment]
Hi, @naitiknakrani-eic can you post the following so we can try to reproduce this?
Rosbag containing:
1. real sense stereoimages
2. Tof images
3. Tf
Launch file
Nvblox config file

**Comment by naitiknakrani-eic** [comment]
Thank you @alexmillane and @ashwinvkNV for your support. The time sync between depth and camera_info works for us and nvblox gave voxel map.
