### ISSUE TITLE
Visualize nav2 costmaps

### ISSUE THREAD

**Issue by sandeepdutta** [NVIDIA-ISAAC-ROS/isaac_ros_nvblox#97]
Hello,

Is there a way to visualize the nav2 costmaps generated by nvblox ? I am specifically
interested in visualizing /nvblox_node/static_map_slice (Type: nvblox_msgs/msg/DistanceMapSlice)

Thank you
Sandeep

**Comment by sandeepdutta** [comment]
I can visualize after starting the nav2 stack.

**Comment by gOrca** [comment]
@sandeepdutta I am currently running ROS2 + NVblox + NVblox Nav2 plugin + Nav2, but am unable to visualize the /nvblox_node/static_map_slice: it simply does not show up in RViz. However, the "...esdf_pointcloud" does show up. 
Is this similar to the original issue that you had? 
If so, could you share how your were able to resolve this?
